#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re


def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    
    try: 
        cmd, payload = dados.split(b' ',1)
    except:
        cmd,payload = dados.split[0] 

    if dados == b'':
        return sair(conexao)
    if cmd == b"PING":
        conexao.enviar(b':server PONG server:' + payload)

    # if dados.split(b' ',1)[0] == b"NICK":

    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
